name       : python-decorator
version    : 4.4.2
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/d/decorator/decorator-4.4.2.tar.gz : e3a62f0520172440ca0dcc823749319382e377f37f140a0b99ef45fecb84bfe7
homepage   : https://github.com/micheles/decorator
license    : BSD-2-Clause
component  : programming.python
summary    : Better living through Python with decorators
description: |
    The aim of the decorator module is to simplify the usage of decorators for the average programmer, and to popularize decorators usage giving examples of useful decorators, such as memoize, tracing, redirecting_stdout, locked, etc. The core of this module is a decorator factory called decorator.
replaces   : 
    - python3-decorator
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
