name       : python-decorator
version    : 4.3.2
release    : 6
source     :
    - https://github.com/micheles/decorator/archive/4.3.2.tar.gz : c053ec881270608a5aef624a45a7700ec76ceca9d96689506411e1f319085380
license    : BSD-2-Clause
component  : programming.python
summary    : Better living through Python with decorators
description: |
    The aim of the decorator module is to simplify the usage of decorators for
    the average programmer, and to popularize decorators usage giving examples
    of useful decorators, such as memoize, tracing, redirecting_stdout, locked,
    etc.  The core of this module is a decorator factory called decorator.
replaces   : python3-decorator
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
