name       : python-decorator
version    : 5.1.1
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/d/decorator/decorator-5.1.1.tar.gz : 637996211036b6385ef91435e4fae22989472f9d571faba8927ba8253acbc330
homepage   : https://github.com/micheles/decorator
license    : BSD-2-Clause
component  : programming.python
summary    : Better living through Python with decorators
description: |
    The aim of the decorator module is to simplify the usage of decorators for the average programmer, and to popularize decorators usage giving examples of useful decorators, such as memoize, tracing, redirecting_stdout, locked, etc. The core of this module is a decorator factory called decorator.
replaces   :
    - python3-decorator
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
